import java.io.*;
class j
{
public static void main(String a[])throws IOException
{
BufferedReader b=new BufferedReader(new InputStreamReader(System.in));
int pa=0,sc=0,ro=0,i=0;
String s[]=new String[3];;
for(i=0;i<3;i++)
{
s[i]=b.readLine();
if(s[i].compareTo("paper")==0)
pa++;
if(s[i].compareTo("scissors")==0)
sc++;
if(s[i].compareTo("rock")==0)
ro++;
}
if((pa==1&&sc==1&&ro==1)||(pa==3||sc==3||ro==3))
{
System.out.print("?");
System.exit(0);
}
else
{
if(pa==2&&ro==1)
{
System.out.print("?");
System.exit(0);
}
if(pa==2&&sc==1)
{
if(s[0].compareTo("scissors")==0)
System.out.print("F");
if(s[1].compareTo("scissors")==0)
System.out.print("M");
if(s[2].compareTo("scissors")==0)
System.out.print("S");
System.exit(0);
}
if(sc==2&&pa==1)
{
System.out.print("?");
System.exit(0);
}
if(sc==2&&ro==1)
{
if(s[0].compareTo("rock")==0)
System.out.print("F");
if(s[1].compareTo("rock")==0)
System.out.print("M");
if(s[2].compareTo("rock")==0)
System.out.print("S");
System.exit(0);
}
if(ro==2&&sc==1)
{
System.out.print("?");
System.exit(0);
}
if(ro==2&&pa==1)
{
if(s[0].compareTo("paper")==0)
System.out.print("F");
if(s[1].compareTo("paper")==0)
System.out.print("M");
if(s[2].compareTo("paper")==0)
System.out.print("S");
System.exit(0);
}
}
}
}