import java.io.*;
class j
{
public static void main(String a[])throws IOException
{
BufferedReader b=new BufferedReader(new InputStreamReader(System.in));
int j=0,lcm=0,k=0,t=0,p=0,n=0,m=0,x=0,i=0;
k=Integer.parseInt(b.readLine());
String s,r;
r=b.readLine();
s=b.readLine();
m=r.length();
n=s.length();
x=(m>n)?m:n;
for(j=x;;j++)
if(j%m==0&&j%n==0)
{lcm=j;break;}
if(k>lcm)
{
for(i=0;i<lcm;i++)
{
if(r.charAt(i%m)!=s.charAt(i%n))
{
if(r.charAt(i%m)=='R'&&s.charAt(i%n)=='P')
p++;
if(r.charAt(i%m)=='R'&&s.charAt(i%n)=='S')
t++;
if(r.charAt(i%m)=='P'&&s.charAt(i%n)=='R')
t++;
if(r.charAt(i%m)=='P'&&s.charAt(i%n)=='S')
p++;
if(r.charAt(i%m)=='S'&&s.charAt(i%n)=='P')
t++;
if(r.charAt(i%m)=='S'&&s.charAt(i%n)=='R')
p++;
}
}
p*=(k/lcm);
t*=(k/lcm);
j=k%lcm;
for(i=0;i<j;i++)
{
if(r.charAt(i%m)!=s.charAt(i%n))
{
if(r.charAt(i%m)=='R'&&s.charAt(i%n)=='P')
p++;
if(r.charAt(i%m)=='R'&&s.charAt(i%n)=='S')
t++;
if(r.charAt(i%m)=='P'&&s.charAt(i%n)=='R')
t++;
if(r.charAt(i%m)=='P'&&s.charAt(i%n)=='S')
p++;
if(r.charAt(i%m)=='S'&&s.charAt(i%n)=='P')
t++;
if(r.charAt(i%m)=='S'&&s.charAt(i%n)=='R')
p++;
}
}
}
else
{
for(i=0;i<k;i++)
{
if(r.charAt(i%m)!=s.charAt(i%n))
{
if(r.charAt(i%m)=='R'&&s.charAt(i%n)=='P')
p++;
if(r.charAt(i%m)=='R'&&s.charAt(i%n)=='S')
t++;
if(r.charAt(i%m)=='P'&&s.charAt(i%n)=='R')
t++;
if(r.charAt(i%m)=='P'&&s.charAt(i%n)=='S')
p++;
if(r.charAt(i%m)=='S'&&s.charAt(i%n)=='P')
t++;
if(r.charAt(i%m)=='S'&&s.charAt(i%n)=='R')
p++;
}
}
}
System.out.print(p+" "+t);
}
}