#include<stdio.h>
int main()
{
long long int type=0,mod=0,set=0,n=0,i=0,k=0,m=0;
scanf("%I64d",&n);
for(i=0;i<n;i++)
{
scanf("%I64d%I64d",&k,&m);
if(k==1)
{
printf("Male\n");
continue;
}
if(k==2)
{
if(m==1||m==4)
printf("Male\n");
else
printf("Female\n");
continue;
}
if(k==3)
{
if(m==1||m==4||m==6||m==7)
printf("Male\n");
else
printf("Female\n");
continue;
}
set=(long long int)ceil((double)m/16);
type=set%2;
mod=m%16;
if(type==1)
{
if(mod==1||mod==4||mod==6||mod==7||mod==10||mod==11||mod==13||mod==0)
printf("Male\n");
else
printf("Female\n");
}
if(type==2)
{
if(mod==1||mod==4||mod==6||mod==7||mod==10||mod==11||mod==13||mod==0)
printf("Female\n");
else
printf("Male\n");
}
}
return 0;
}