import java.io.*;
class j
{
public static void main(String a[])throws IOException
{
BufferedReader b=new BufferedReader(new InputStreamReader(System.in));
int i=0,m=0,n=0,k=0,u=0,v=0,w=0,x=0;
String r,s;
r=b.readLine();
s=b.readLine();
r=r.replace('a','1');
s=s.replace('a','1');
r=r.replace('b','2');
s=s.replace('b','2');
r=r.replace('c','3');
s=s.replace('c','3');
r=r.replace('d','4');
s=s.replace('d','4');
r=r.replace('e','5');
s=s.replace('e','5');
r=r.replace('f','6');
s=s.replace('f','6');
r=r.replace('g','7');
s=s.replace('g','7');
r=r.replace('h','8');
s=s.replace('h','8');
u=Integer.parseInt(r.substring(0,1));
v=Integer.parseInt(r.substring(1,2));
w=Integer.parseInt(s.substring(0,1));
x=Integer.parseInt(s.substring(1,2));
m=(int)Math.abs(u-w);
n=(int)Math.abs(v-x);
k=(m>n)?m:n;
System.out.println(k);
for(i=0;i<k;i++)
{
if(u<w&&v<x)
{
System.out.println("RU");
u++;
v++;
}
if(u>w&&v>x)
{
System.out.println("LD");
u--;
v--;
}
if(u<w&&v>x)
{
System.out.println("RD");
u++;
v--;
}
if(u>w&&v<x)
{
System.out.println("LU");
u--;
v++;
}
if(u==w&&v<x)
{
System.out.println("U");
v++;
}
if(u==w&&v>x)
{
System.out.println("D");
v--;
}
if(u>w&&v==x)
{
System.out.println("L");
u--;
}
if(u<w&&v==x)
{
System.out.println("R");
u++;
}
}
}
}